baseURL = "https://whobbes.com/blog/"
languageCode = "en-gb"
title = "Whobbes.com/blog"
theme = "kiera"
buildDrafts = false
canonifyURLs = true
copyright = "Copyright &copy; Wallace Hobbes. All rights reserved."

contentDir = "content"
layoutDir = "layouts"
publishDir = "../whobbes.github.io/blog"
pygmentsCodeFences = true
disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Wallace"       #Author name
    github = "whobbes"     #Github username
    linkedin = "sylvainviguier"   #LinkedIn username
    twitter = "wallacehobbes"    #Twitter username
    instagram = "wallacehobbes"  #Instagram username
    home = "http://whobbes.com"

[params]
    tagline = "Creative Scientist"

[taxonomies]
	category = "categories"
	tag = "tags"

